#*      makefile
#*
#* Make script for build options - only does cleanup
#*
#* $Id: makefile,v 1.2 1997/07/31 10:56:34 pekangas Exp $
#*
#* Copyright 1996,1997 Housemarque Inc.
#*
#* This file is part of MIDAS Digital Audio System, and may only be
#* used, modified and distributed under the terms of the MIDAS
#* Digital Audio System license, "license.txt". By continuing to use,
#* modify or distribute this file you indicate that you have
#* read the license and understand and accept it fully.
#*

# Include build options:
BLDOPTSDIR=.
MIDASDIR=..
include $(BLDOPTSDIR)/bldopts.mak


# Default target (dummy to make sure we won't accidentally delete anything):
all :

# Cleanup:
clean distclean cvsclean :
	$(CLEANALL)



